name: SonarQube Analysis

on:
  push:
    branches:
      - master  # Ajusta según tu rama principal

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml  # Ajusta la ruta a tu código

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=proyecto-python \
            -Dsonar.organization=tu-org \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.python.version=3.10 \
            -Dsonar.coverageReportPaths=coverage.xml
